
plan:
  aws:
    roles:
      - { name: 'front', image: 'front.ami', type: 'ec2', ttl: '1' }
      - { name: 'worker', image: 'worker.ami', type: 'ec2', ttl: '1' }
    aws_settings:
      access_key_id: 'access id'
      secret_access_key: 'your key'
      todo: '< READ ^ Secrets from ENV or Valve >'
